name = "koreader-sync-rs"
main = "build/worker/shim.mjs"
compatibility_date = "2024-08-25"

[build]
command = "cargo install -q worker-build --version '^0.1' && worker-build --release"

[vars]
REGISTRATION="enabled"

[[d1_databases]]
binding = "DB_PROD_KOSYNC"
database_name = "prod-kosync"
database_id = "f3551805-6297-4ff5-a09c-f601e4a66e77"
